driver_plugin: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12
  client_rb:
    environment: kitchen

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    encrypted_data_bag_secret_key_path: "~/.chef/encrypted_data_bag_secret"
    data_bags_path: "../..//data_bags" 
